#!/usr/bin/env bash
#
# Regenerates BLEKitCore's Bluetooth SIG UUID -> name tables from the canonical
# assigned-numbers YAML published by the Bluetooth SIG.
#
#   https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/uuids/
#
# Output: BLEKit/Sources/BLEKitCore/AssignedNumbers/GATTAssignedNumbers+Generated.swift
#
# Requires: bash, curl, python3 (all preinstalled on macOS; stdlib only).
# Re-running with no upstream change leaves `git diff` empty.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="$REPO_ROOT/BLEKit/Sources/BLEKitCore/AssignedNumbers/GATTAssignedNumbers+Generated.swift"
BASE_URL="https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers/uuids"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

for registry in service_uuids characteristic_uuids descriptors; do
    echo "Fetching $registry.yaml ..." >&2
    curl -fsSL "$BASE_URL/$registry.yaml" -o "$WORK_DIR/$registry.yaml"
done

mkdir -p "$(dirname "$OUT_FILE")"

python3 - "$WORK_DIR" "$OUT_FILE" <<'PY'
import datetime
import sys

work_dir, out_file = sys.argv[1], sys.argv[2]

REGISTRIES = [
    ("service_uuids.yaml", "serviceNames"),
    ("characteristic_uuids.yaml", "characteristicNames"),
    ("descriptors.yaml", "descriptorNames"),
]


def parse(path):
    """Scan the flat SIG YAML: a `- uuid: 0x....` line paired with its next `name:` line."""
    entries = {}
    current = None
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            stripped = line.strip()
            if stripped.startswith("- uuid:") or stripped.startswith("uuid:"):
                value = stripped.split(":", 1)[1].strip()
                current = int(value, 16)
            elif stripped.startswith("name:") and current is not None:
                name = stripped.split(":", 1)[1].strip()
                name = name.replace("\\", "\\\\").replace('"', '\\"')
                entries[current] = name
                current = None
    if not entries:
        raise SystemExit(f"no entries parsed from {path}")
    return entries


lines = [
    "// Generated by scripts/generate-assigned-numbers.sh — do not edit.",
    "// Source: Bluetooth SIG assigned_numbers — https://bitbucket.org/bluetooth-SIG/public",
    f"// Generated: {datetime.date.today().isoformat()}",
    "",
    "import Foundation",
    "",
    "extension GATTAssignedNumbers {",
]

for index, (filename, swift_name) in enumerate(REGISTRIES):
    entries = parse(f"{work_dir}/{filename}")
    lines.append(f"    static let {swift_name}: [UInt32: String] = [")
    for key in sorted(entries):
        lines.append(f'        0x{key:04X}: "{entries[key]}",')
    lines.append("    ]")
    if index != len(REGISTRIES) - 1:
        lines.append("")

lines.append("}")
lines.append("")

with open(out_file, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines))

print(f"Wrote {out_file}", file=sys.stderr)
PY

echo "Done." >&2
